### ISSUE TITLE
getting this error while trying to run the main.py

### ISSUE THREAD

**Issue by chloe27anne** [thuccj/Pegaxy_Racing_bot#1]
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    main()
  File "main.py", line 106, in main
    images = load_screenshots()
  File "main.py", line 46, in load_screenshots
    targets[file.removesuffix('.png')] = cv2.imread(path)
AttributeError: 'str' object has no attribute 'removesuffix'

**Comment by thuccj** [comment]
I don't have that error! 😢
- You can try to fix it here: https://stackoverflow.com/questions/66683630/removesuffix-returns-error-str-object-has-no-attribute-removesuffix
- Or: create its own removeuffix function
``` python
def remove_suffix(input_string, suffix):
    if suffix and input_string.endswith(suffix):
        return input_string[:-len(suffix)]
    return input_string
```

**Comment by thuccj** [comment]
> Traceback (most recent call last): File "main.py", line 196, in main() File "main.py", line 106, in main images = load_screenshots() File "main.py", line 46, in load_screenshots targets[file.removesuffix('.png')] = cv2.imread(path) AttributeError: 'str' object has no attribute 'removesuffix'

I don't have that error! 😢
- You can try to fix it here: https://stackoverflow.com/questions/66683630/removesuffix-returns-error-str-object-has-no-attribute-removesuffix
- Or: create its own removeuffix function
``` python
def remove_suffix(input_string, suffix):
    if suffix and input_string.endswith(suffix):
        return input_string[:-len(suffix)]
    return input_string
```

**Comment by thuccj** [comment]
> Traceback (most recent call last): File "main.py", line 196, in main() File "main.py", line 106, in main images = load_screenshots() File "main.py", line 46, in load_screenshots targets[file.removesuffix('.png')] = cv2.imread(path) AttributeError: 'str' object has no attribute 'removesuffix'

### Hmmmh. Did you update new images on website game in the screenshots folder??

**Comment by thuccj** [comment]
> Traceback (most recent call last): File "main.py", line 196, in main() File "main.py", line 106, in main images = load_screenshots() File "main.py", line 46, in load_screenshots targets[file.removesuffix('.png')] = cv2.imread(path) AttributeError: 'str' object has no attribute 'removesuffix'

### I don't have that error! 😢
- You can try to fix it here: https://stackoverflow.com/questions/66683630/removesuffix-returns-error-str-object-has-no-attribute-removesuffix
- Or: create its own removeuffix function and use it
``` python
def remove_suffix(input_string, suffix):
    if suffix and input_string.endswith(suffix):
        return input_string[:-len(suffix)]
    return input_string
```
Example:
- Variable "input_string" is variable "file" in my code
- Variable "suffix" is '.png'

**Comment by chloe27anne** [comment]
Hi, thanks for the response.. sorry im dont fully understand coding.. so it should be something like this?

def remove_suffix(file,'.png'):
    if suffix and input_string.endswith(suffix):
        return input_string[:-len(suffix)]
    return input_string
    
    
    and which line should i put it in the code?
    
    Also can i ask what version of python do you have?

**Comment by thuccj** [comment]
> Hi, thanks for the response.. sorry im dont fully understand coding.. so it should be something like this?
> 
> def remove_suffix(file,'.png'): if suffix and input_string.endswith(suffix): return input_string[:-len(suffix)] return input_string
> 
> ```
> and which line should i put it in the code?
> 
> Also can i ask what version of python do you have?
> ```

No 😢

### - You can fix my code like here:
```python
my code ...

def remove_suffix(input_string, suffix):
    if suffix and input_string.endswith(suffix):
        return input_string[:-len(suffix)]
    return input_string

def load_screenshots(dir_path='./screenshots/'):

    file_names = listdir(dir_path)
    targets = {}
    for file in file_names:
        path = 'screenshots/' + file
        targets[remove_suffix(file, '.png'] = cv2.imread(path)

    return targets

my code ...
```

### - When you run the requirements.txt file. It's fully equipped
### - I use lastest version python
